name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  change-detection:
    name: 🔍 Change
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-change-detection.yml@99af11652a4238dbe50ebe4b003a9f0fd5fb8085 # v2.4.1
    permissions:
      contents: read

  python-tests:
    name: 🐍 Test
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm, macos-26, windows-2025]
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-tests.yml@99af11652a4238dbe50ebe4b003a9f0fd5fb8085 # v2.4.1
    with:
      runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read

  python-coverage:
    name: 🐍 Coverage
    needs: [change-detection, python-tests]
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-coverage.yml@99af11652a4238dbe50ebe4b003a9f0fd5fb8085 # v2.4.1
    permissions:
      contents: read
      id-token: write

  python-linter:
    name: 🐍 Lint
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-linter)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-linter.yml@99af11652a4238dbe50ebe4b003a9f0fd5fb8085 # v2.4.1
    with:
      enable-ty: true
      enable-mypy: false
    permissions:
      contents: read

  build-sdist:
    name: 🚀 CD
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cd)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-packaging-sdist.yml@99af11652a4238dbe50ebe4b003a9f0fd5fb8085 # v2.4.1
    permissions:
      contents: read

  build-wheel:
    name: 🚀 CD
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cd)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-packaging-wheel-build.yml@99af11652a4238dbe50ebe4b003a9f0fd5fb8085 # v2.4.1
    permissions:
      contents: read

  # this job does nothing and is only used for branch protection
  required-checks-pass:
    name: 🚦 Check
    if: always()
    needs:
      - change-detection
      - python-tests
      - python-coverage
      - python-linter
      - build-sdist
      - build-wheel
    runs-on: ubuntu-slim
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          allowed-skips: >-
            ${{
              !fromJSON(needs.change-detection.outputs.run-python-tests)
              && 'python-tests,python-coverage,' || ''
            }}
            ${{
              !fromJSON(needs.change-detection.outputs.run-python-linter)
              && 'python-linter,' || ''
            }}
            ${{
              !fromJSON(needs.change-detection.outputs.run-cd)
              && 'build-sdist,build-wheel' || ''
            }}
          jobs: ${{ toJSON(needs) }}
