name: Test run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_bindings:
    name: Run script on example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.10"
      - name: Install package
        run: |
          pip install -U pip setuptools wheel
          pip install .
          
      # Test the first script (run.py)
      - name: Test run.py
        run: |
          python run.py --help
          python run.py algorithms/qft_05.json
          
      # Test the second script (run_heuristic.py)
      - name: Test run_heuristic.py
        run: |
          python run_heuristic.py --help
          python run_heuristic.py algorithms_heuristic/qft_6.json
